RustCrypto/AEADs

- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/cipher.rs
- chacha20poly1305/src/lib.rs
- chacha20poly1305/src/xchacha20poly1305.rs
- chacha20poly1305/tests/lib.rs
This updates `chacha20poly1305` to switch to the newly released `aead` crate.
> chacha20poly1305: Use 0.1 release of `aead` crate

- chacha20poly1305/src/xchacha20poly1305.rs
The docs cite libsodium as another implementor of the somewhat underspecified XChaCha20Poly1305 algorithm, but I overinterpreted that as suggesting that this crate was a suitable replacement for libsodium's `secretbox` functionality.
It turns out that libsodium provides *two* algorithms under the "secretbox" category: XSalsa20Poly1305 (the default), and XChaCha20Poly1305 (a newer addition). This crate might be compatible with XChaCha20Poly1305, but alas it is not compatible with XSalsa20Poly1305. (Apparently the key and nonce sizes are the same, so you might not notice a problem until your test vectors fail to match). My library (magic-wormhole) is using `secretbox`, so for backwards compatibility reasons I have to stick with the salsa variant, thwarting my plans to replace my libsodium …
> document the incompatibility with libsodium 'secretbox'

- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- Update to `zeroize` 1.0.0-pre ([#17])
[#17]: https://github.com/RustCrypto/AEADs/pull/17
> chacha20poly1305 v0.1.2

- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- chacha20poly1305/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Upgrades `aes-gcm-siv` to use `polyval` crate v0.2, and the `chacha20poly1305` and `xsalsa20poly1305` crates to use `poly1305` v0.5.
The new `polyval` and `poly1305` crates transitively depend on `universal-hash` v0.3.
> Upgrade to `universal-hash` crate v0.3

- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/ctr32.rs
- aes-gcm-siv/src/lib.rs
- chacha20poly1305/src/cipher.rs
- chacha20poly1305/src/lib.rs
- chacha20poly1305/src/xchacha20poly1305.rs
- xsalsa20poly1305/src/lib.rs
Exposes an `encrypt_in_place_detached()` and `decrypt_in_place_detached()` API on all AEAD implementations in this repository.
Until we figure out what the upstream API looks like, this commit at least makes an in-place mode an option for those who don't want to allocate a buffer for every encryption/decryption operation.
> Expose "detached" in-place encryption/decryption APIs

- aes-gcm-siv/Cargo.toml
https://github.com/RustCrypto/universal-hashes/pull/29
> aes-gcm-siv: Upgrade to `polyval` v0.3

- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- xsalsa20poly1305/Cargo.toml
- Expose "detached" in-place encryption/decryption APIs ([#21])
- Upgrade to `poly1305` crate v0.5 ([#20])
[#21]: https://github.com/RustCrypto/AEADs/pull/21
[#20]: https://github.com/RustCrypto/AEADs/pull/20
> chacha20poly1305 v0.2.0

- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
- Expose "detached" in-place encryption/decryption APIs ([#21])
- Upgrade to `poly1305` crate v0.5 ([#20])
[#21]: https://github.com/RustCrypto/AEADs/pull/21
[#20]: https://github.com/RustCrypto/AEADs/pull/20
> xsalsa20poly1305 v0.2.0

- Cargo.toml
- aes-siv/CHANGELOG.md
- aes-siv/Cargo.toml
- aes-siv/LICENSE-APACHE
- aes-siv/LICENSE-MIT
- aes-siv/README.md
- aes-siv/src/lib.rs
- aes-siv/src/siv.rs
- aes-siv/tests/aead.rs
- aes-siv/tests/siv.rs
- aes-siv/tests/vectors/aead.rs
- aes-siv/tests/vectors/mod.rs
- aes-siv/tests/vectors/siv.rs
This is largely an import of the AES-(PMAC-)SIV implementation from Miscreant, taken from this commit:
https://github.com/miscreant/miscreant.rs/commit/71aa57519347d0b6a38204f86f2f0335756ae0b8
It uses the `AeadMut` API for now (but would be nice to convert to `Aead` eventually)
Note that the RFC 5297 description of the AEAD interface for AES-SIV cannot presently be expressed in terms of the `Aead`/`AeadMut` traits, since it supports a variable-length nonce (which is what Miscreant's current `Aead` trait also provides):
https://tools.ietf.org/html/rfc5297#section-6.1
> N_MIN  is 1 octet.
> N_MAX  is unlimited.
I have selected a 128-bit `NonceSize` based on the following SHOULD in RFC 5297:
https://tools.ietf.org/html/rfc5297#section-3
> If the nonce is random, it SHOULD be at least 128 …
> AES-SIV and AES-PMAC-SIV

- chacha20poly1305/src/lib.rs
- chacha20poly1305/src/xchacha20poly1305.rs
- Fix reference to XSalsa20Poly1305 instead of XChaCha20Poly1305
- Link to the `xsalsa20poly1305` crate
> chacha20poly1305: documentation improvements

- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/README.md
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/xchacha20poly1305.rs
- xsalsa20poly1305/Cargo.toml
This removes the `-pre` from the requirements for all crates which are using it. Due to semver all of these crates are already using `zeroize` 1.0 anyway, however this officially codifies it in the `Cargo.toml` files.
(Additionally I included some documentation updates in this PR. Mea culpa for not splitting it out separately, but I hope no one cares)
> Upgrade to `zeroize` 1.0

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
> aes-gcm v0.1.1

- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
> aes-gcm-siv v0.2.1

- aes-siv/CHANGELOG.md
- aes-siv/Cargo.toml
> aes-siv v0.1.2

- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- aes-gcm/Cargo.toml
- aes-gcm/src/lib.rs
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/cipher.rs
- chacha20poly1305/src/lib.rs
- chacha20poly1305/src/xchacha20poly1305.rs
- xsalsa20poly1305/Cargo.toml
- xsalsa20poly1305/src/lib.rs
Note: I was not able to upgrade aead for `aes-siv` crate. I'll probably need some help doing it. 
Also, in `xsalsa20poly1305`, I suspect `XSalsa20Poly1305::encrypt()` and `XSalsa20Poly1305::encrypt_in_place()` will give different results because, in `XSalsa20Poly1305::encrypt()`, `tag` is inserted before the encrypted data and `XSalsa20Poly1305::encrypt_in_place()` which is auto-implemented from `Aead` trait appends `tag` at the end of the buffer.
> Upgrade aead to v0.2

- aes-siv/src/lib.rs
- aes-siv/src/siv.rs
- aes-siv/tests/siv.rs
Replaces the panicking slice-based interface with one which calculates a GenericArray size using typenum-based arithmetic.
A bit gross for now, but should be nice when const generics happen.
> aes-siv: make `Siv::new` type-safe via typenum arithmetic

- xsalsa20poly1305/Cargo.toml
- xsalsa20poly1305/src/lib.rs
These were using the default impls of the non-detached in-place API, which use a postfix (as opposed to prefix tag).
By impling these APIs, we can use the default allocating ones.
> xsalsa20poly1305: fix in-place (non-detached) API

- aes-siv/src/lib.rs
- aes-siv/src/siv.rs
Changes the AEAD interface to reinstantiate the `Siv` interface (which needs `&mut` refs) every time an `encrypt*` or `decrypt*` method is called.
By doing this, the `SivAead` interface can impl `Aead` rather than `AeadMut`, which is more flexible / thread safe.
> aes-siv: Switch from AeadMut to Aead

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Upgrade `aead` crate to v0.2; `alloc` now optional ([#43])
[#43]: https://github.com/RustCrypto/AEADs/pull/43
> aes-gcm v0.2.0

- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- aes-gcm/src/lib.rs
- aes-siv/src/lib.rs
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/lib.rs
- xsalsa20poly1305/src/lib.rs
All crates in this repo now have an optional `alloc` feature which can be disabled for use in heapless environments.
> alloc-free usage notes and fixups for all crates

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Document in-place API ([#49])
[#49]: https://github.com/RustCrypto/AEADs/pull/49
> aes-gcm v0.2.1

- .travis.yml
- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- aes-gcm/Cargo.toml
- aes-gcm/src/lib.rs
- aes-siv/Cargo.toml
- aes-siv/src/lib.rs
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/lib.rs
- xsalsa20poly1305/Cargo.toml
- xsalsa20poly1305/src/lib.rs
Makes `heapless` a first-class feature on all crates, to simplify heapless usage (e.g. microcontrollers).
With `heapless` as a first-class feature, it becomes possible to explicitly document heapless usage as well, which this commit also does.
> Add a `heapless` feature to all crates + docs to use it

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- `heapless` feature ([#51])
[#51]: https://github.com/RustCrypto/AEADs/pull/51
> aes-gcm v0.3.0

- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- `heapless` feature ([#51])
- Upgrade `aead` crate to v0.2; `alloc` now optional ([#43])
[#51]: https://github.com/RustCrypto/AEADs/pull/51
[#43]: https://github.com/RustCrypto/AEADs/pull/43
> aes-gcm-siv v0.3.0

- aes-siv/CHANGELOG.md
- aes-siv/Cargo.toml
- `heapless` feature ([#51])
- Switch from `AeadMut` to `Aead` ([#47])
- Make `Siv::new` type-safe via `typenum` arithmetic ([#45])
- Upgrade `aead` crate to v0.2; `alloc` now optional ([#44])
[#51]: https://github.com/RustCrypto/AEADs/pull/51
[#47]: https://github.com/RustCrypto/AEADs/pull/47
[#45]: https://github.com/RustCrypto/AEADs/pull/45
[#44]: https://github.com/RustCrypto/AEADs/pull/44
> aes-siv v0.2.0

- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
- `heapless` feature ([#51])
- Upgrade `aead` crate to v0.2; `alloc` now optional ([#43])
[#51]: https://github.com/RustCrypto/AEADs/pull/51
[#43]: https://github.com/RustCrypto/AEADs/pull/43
> xsalsa20poly1305 v0.3.0

- .travis.yml
- README.md
- aes-gcm-siv/README.md
- aes-gcm/README.md
- aes-siv/README.md
- aes-siv/src/siv.rs
- chacha20poly1305/README.md
- xsalsa20poly1305/README.md
- xsalsa20poly1305/src/lib.rs
`aes-siv` and `xsalsa20poly1305` use a prepended authentication tag, which means during in-place encryption/decryption, they need the message shifted by the tag size.
It would be nice if this could happen during encryption/decryption:
https://github.com/RustCrypto/block-ciphers/issues/59
...but barring that, using `copy_within` (which performs a `memmove` behind the scenes) should be the fastest available option.
This commit replaces a previous `for` loop which performed this copy with `copy_within`.
Note that `copy_within` is MSRV 1.37+, so this bumps the project MSRV up by a single version (from 1.36).
> Use `copy_within` for `aes-siv`/`xsalsa20poly1305`; MSRV 1.37+

- README.md
It supports the `aead` crate's traits, so is otherwise "compatible" with the other crates in this project, but maintained by a 3rd party.
> README.md: Add link to `aes-ccm` crate

- README.md
Previously the main "call to action" to me for the table is to click the link to the algorithm info (e.g. Wikipedia, RFCs), which probably isn't where the user wants to go.
> README.md: Add crate names to table

- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- chacha20poly1305/Cargo.toml
- chacha20poly1305/benches/aes-gcm.rs
Adds a `criterion` benchmark similar to the `aes-gcm` and `aes-gcm-siv` crate, with the cycles-per-byte plugin enabled.
> chacha20poly1305: add benchmark

- chacha20poly1305/Cargo.toml
This results in a ~60% performance boost for encryption when the AVX2 backend is enabled.
Decryption performance is unaffected.
> chacha20poly1305: upgrade to `chacha20` v0.3

- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/lib.rs
Adds `ChaCha8Poly1305` and `ChaCha12Poly1305` AEADs, gated under the (off-by-default) `reduced-round` cargo feature.
See the writeup I've already done for the `rand_chacha` crate for the rationale of including these by default:
https://github.com/rust-random/rand/issues/932
tl;dr: the "Too Much Crypto" paper goes into why ChaCha20 is overkill, ChaCha12 is probably what should've been standardized per the eSTREAM analysis of Salsa20 (but wasn't for cargo cult reasons), and ChaCha8 is still probably safe:
https://eprint.iacr.org/2019/1492
> chacha20poly1305: Add ChaCha8/ChaCha20 reduced round variants

- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- chacha20poly1305/README.md
- `ChaCha8Poly1305`/`ChaCha12Poly1305` reduced round variants ([#69])
- `criterion`-based benchmark ([#66])
- Upgrade to `chacha20` v0.3; adds AVX2 backend w\ +60% perf ([#67])
[#66]: https://github.com/RustCrypto/AEADs/pull/66
[#67]: https://github.com/RustCrypto/AEADs/pull/67
[#69]: https://github.com/RustCrypto/AEADs/pull/69
> chacha20poly1305 v0.3.1

- aes-gcm/Cargo.toml
- aes-gcm/README.md
- aes-gcm/src/lib.rs
- chacha20poly1305/Cargo.toml
- chacha20poly1305/README.md
- chacha20poly1305/src/cipher.rs
- chacha20poly1305/src/lib.rs
Updates the README.md files and crate documentation for the `aes-gcm` and `chacha20poly1305` crates to reflect the NCC audit findings:
https://research.nccgroup.com/2020/02/26/public-report-rustcrypto-aes-gcm-and-chacha20poly1305-implementation-review/
> aes-gcm/chacha20poly1305: add NCC audit notes to doc

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- aes-gcm/README.md
- aes-gcm/src/lib.rs
- chacha20poly1305/Cargo.toml
- Notes about NCC audit to documentation ([#80])
[#80]: https://github.com/RustCrypto/AEADs/pull/80
> aes-gcm v0.3.1

- README.md
We're now in a state where `aes-gcm` and `chacha20poly1305` have been audited, but the other implementations have not.
Every crate already carries its own notice about whether it has or has not been audited, so this commit removes the toplevel notice.
> README.md: remove (toplevel) security warning

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Wording in documentation about security audit ([#84])
[#84]: https://github.com/RustCrypto/AEADs/pull/84
> aes-gcm v0.3.2

- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- chacha20poly1305/README.md
- chacha20poly1305/src/lib.rs
- Wording in documentation about security audit ([#84])
[#84]: https://github.com/RustCrypto/AEADs/pull/84
> chacha20poly1305 v0.3.3

- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/ctr32.rs
- aes-gcm-siv/src/lib.rs
The use case is instantiating AES-GCM-SIV using an embedded cryptographic processor (including one where the key is hardware-backed and deliberately inextricable)
See: https://github.com/iqlusioninc/usbarmory.rs/pull/41
> aes-gcm-siv: support instantiation from an existing (AES) block cipher instance

- aes-gcm-siv/src/ctr.rs
- aes-gcm-siv/src/lib.rs
Eliminates `C: Ctr` as an external generic parameter by making the implementation generic around the number of parallel blocks.
> aes-gcm-siv: make `Ctr32` generic around `B::ParBlocks`

- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/README.md
- aes-gcm-siv/src/lib.rs
A recent audit by NCC group covered the dependencies shared between the `aes-gcm` and `aes-gcm-siv` crates, namely the `aes` crate (and its dependencies) as well as the `polyval` crate, which is used by the `aes-gcm` crate to implement GHASH:
https://research.nccgroup.com/2020/02/26/public-report-rustcrypto-aes-gcm-and-chacha20poly1305-implementation-review/
Note that the `aes-gcm-siv` crate itself was *NOT* audited.
This commit updates the README.md files and crate documentation for the `aes-gcm-siv` to note that the `aes` crate and `polyval` crate were audited, but that the `aes-gcm-siv` crate itself has *NOT* been audited.
It also updates the `maintenance` badge from `experimental` to `actively-developed`.
> aes-gcm-siv: add NCC audit notes to docs

- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- `aes` cargo feature; 3rd-party AES crate support ([#90])
- Make generic around `BlockCipher::ParBlocks` ([#91], [#93])
[#90]: https://github.com/RustCrypto/AEADs/pull/90
[#91]: https://github.com/RustCrypto/AEADs/pull/91
[#93]: https://github.com/RustCrypto/AEADs/pull/93
> aes-gcm-siv v0.4.0

- aes-gcm/Cargo.toml
- aes-gcm/src/ctr.rs
- aes-gcm/src/lib.rs
This commit makes `aes` an optional feature, which is useful when swapping in an alternate (e.g. embedded hardware) implementation of AES as opposed to using the `aes` crate.
> aes-gcm: make `aes` crate optional; semver breaking change

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- `aes` cargo feature; 3rd-party AES crate support ([#96])
- Make generic around `BlockCipher::ParBlocks` ([#97])
[#96]: https://github.com/RustCrypto/AEADs/pull/96
[#97]: https://github.com/RustCrypto/AEADs/pull/97
> aes-gcm v0.4.0

- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/cipher.rs
- chacha20poly1305/src/lib.rs
Makes the `chacha20` dependency optional so it can be swapped out for alternative versions that use e.g. exotic SIMD intrinsics.
Replaces the previous usage of macros to define the various reduced round variants with one based on generic composition which allows for swapping in a different implementation.
> chacha20poly1305: optional `chacha20`; replace macros with generics

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Support instantiation from an existing cipher instance ([#101])
[#101]: https://github.com/RustCrypto/AEADs/pull/101
> aes-gcm v0.4.1

- chacha20poly1305/src/lib.rs
Deriving `Clone` wasn't working because of the `PhantomData` parameter.
> chacha20poly1305: fix clone impl

- aes-gcm-siv/src/ctr.rs
- aes-gcm/src/ctr.rs
This was checking that the number of parallel blocks to be computed doesn't exceed what's supported by the underlying cipher, except it failed in the case that the number of blocks to be computed was equal to the total supported.
> aes-gcm(-siv): fix off-by-one error in ParBlocks `debug_assert`

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Off-by-one error in `debug_assert` for `BlockCipher::ParBlocks` ([#104])
[#104]: https://github.com/RustCrypto/AEADs/pull/104
> aes-gcm v0.4.2

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- aes-gcm/CHANGELOG.md
- Off-by-one error in `debug_assert` for `BlockCipher::ParBlocks` ([#104])
[#104]: https://github.com/RustCrypto/AEADs/pull/104
> aes-gcm-siv v0.4.1

- .github/workflows/aes-gcm-siv.yml
- .github/workflows/aes-gcm.yml
- .github/workflows/aes-siv.yml
- .github/workflows/chacha20poly1305.yml
- .github/workflows/crypto_box.yml
- .github/workflows/ring-aead.yml
- .github/workflows/xsalsa20poly1305.yml
The build badges are broken because of it, and it just makes things a bit harder than necessary
> Remove 'crate' from GitHub Action names

- aes-gcm/src/ctr.rs
- aes-gcm/src/lib.rs
- aes-gcm/tests/other_ivlen.rs
Support for non-96-bit nonces, while still implementing the current `Aead` interface and type safety for nonce lengths.
> aes-gcm: make AesGcm generic around nonce size

- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Support for non-96-bit nonces ([#126])
- `AesGcm` type is now generic around nonce size ([#126])
[#126]:  https://github.com/RustCrypto/AEADs/pull/126
> aes-gcm v0.5.0

- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/README.md
- aes-gcm/Cargo.toml
- aes-gcm/README.md
- aes-siv/Cargo.toml
- aes-siv/README.md
- chacha20poly1305/Cargo.toml
- chacha20poly1305/README.md
- crypto_box/Cargo.toml
- crypto_box/README.md
- ring-aead/Cargo.toml
- ring-aead/README.md
- xsalsa20poly1305/Cargo.toml
- xsalsa20poly1305/README.md
We previously relied on https://crates.io to display this but they removed all badges recently, so this deletes the `[badge]` section of Cargo.toml(s).
This commit adds the badge to all the README.md(s) as this repo has fairly decent (94% at present) code coverage.
> README.md(s): move CodeCov.io badges from Cargo.toml

- Cargo.lock
- Cargo.toml
- aes-gcm/Cargo.toml
- aes-gcm/src/ctr.rs
- aes-gcm/src/lib.rs
- aes-gcm/tests/common/mod.rs
- aes-gcm/tests/other_ivlen.rs
Upgrades to the `aead` v0.3.0-pre crate.
> aes-gcm: `aead` crate upgrade

- Cargo.lock
- Cargo.toml
- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/ctr.rs
- aes-gcm-siv/src/lib.rs
- aes-gcm-siv/tests/common/mod.rs
Bumps the `aead` crate to the v0.3.0-pre release
> aes-gcm-siv: bump `aead` crate

- Cargo.lock
- Cargo.toml
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/cipher.rs
- chacha20poly1305/src/lib.rs
- chacha20poly1305/src/xchacha20poly1305.rs
- chacha20poly1305/tests/lib.rs
Upgrades to the `aead` v0.3.0-pre crate.
> chacha20poly1305: `aead` crate upgrade

- Cargo.lock
- ring-aead/Cargo.toml
- ring-aead/src/lib.rs
- ring-aead/tests/aes128gcm.rs
- ring-aead/tests/aes256gcm.rs
- ring-aead/tests/chacha20poly1305.rs
- ring-aead/tests/common/mod.rs
Upgrades to the `aead` v0.3.0-pre crate.
> ring-aead: `aead` crate upgrade

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- chacha20poly1305/Cargo.toml
- crypto_box/Cargo.toml
- xsalsa20poly1305/Cargo.toml
...to reflect the breaking `aead` crate update
> Bump all versions to `*-pre`

- Cargo.lock
- aes-gcm-siv/src/lib.rs
- aes-gcm/src/lib.rs
- aes-siv/src/siv.rs
- chacha20poly1305/src/cipher.rs
Implements the API changes from:
https://github.com/RustCrypto/traits/pull/161
The `crypto-mac` and `digest` crates now use `update` and `finalize` nomenclature ala the Initialize-Update-Finalize (IUF) interface naming scheme.
> Rename `*result*` to `finalize`

- aes-gcm-siv/src/lib.rs
- aes-gcm/src/lib.rs
- aes-siv/src/lib.rs
- aes-siv/src/siv.rs
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/lib.rs
- chacha20poly1305/src/xchacha20poly1305.rs
- crypto_box/src/lib.rs
- xsalsa20poly1305/src/lib.rs
- Fix links to `AeadInPlace` traits
- Leverage `rustdoc` more rather than using absolute URLs
- Access `aead` crate as a re-export in examples
- Note that `expect` panics in examples
- Add `doc(cfg(...))` for features of the `chacha20poly1305` crate
> Documentation improvements

- chacha20poly1305/src/xchacha20poly1305.rs
See #153. Other crate docs use re-exports.
> Small chacha20poly1305 doc improvement

- Cargo.lock
- Cargo.toml
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- chacha20poly1305/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Updates the following dependencies to use crates.io releases:
- `aes` v0.4.0
- `aes-soft` v0.4.0
- `aesni` v0.7.0
- `block-cipher` v0.7.0
- `cmac` v0.3.0
- `pmac` v0.3.0
- `stream-cipher` v0.4.0
TODO: `universal-hash`es
> Use release versions of crate dependencies

- Cargo.lock
- Cargo.toml
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- chacha20poly1305/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Updates the following UHF deps to use https://crates.io releases:
- `ghash` v0.3.0
- `polyval` v0.4.0
- `poly1305` v0.6.0
> Use release versions of `universal-hash` crates

- Cargo.lock
- Cargo.toml
- aes-siv/Cargo.toml
- chacha20poly1305/Cargo.toml
- crypto_box/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Updates all dependencies from `RustCrypto/stream-ciphers` to releases published to https://crates.io
This removes the `[patch.crates-io]` section and means we can finally release new versions of all crates in this repo 🎉
> Update `stream-cipher` dependencies

- Cargo.lock
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Bump `aead` crate dependency to v0.3.0; MSRV 1.41+ ([#142])
[#142]: https://github.com/RustCrypto/AEADs/pull/126
> aes-gcm v0.6.0

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- aes-gcm/CHANGELOG.md
- Bump `aead` crate dependency to v0.3.0; MSRV 1.41+ ([#142])
[#142]: https://github.com/RustCrypto/AEADs/pull/126
> aes-gcm-siv v0.5.0

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm/CHANGELOG.md
- aes-siv/CHANGELOG.md
- aes-siv/Cargo.toml
- Bump `aead` crate dependency to v0.3.0; MSRV 1.41+ ([#143])
- Use `copy_within` ([#57])
[#143]: https://github.com/RustCrypto/AEADs/pull/143
[#57]: https://github.com/RustCrypto/AEADs/pull/57
> aes-siv v0.3.0

- Cargo.lock
- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- Bump `aead` crate dependency to v0.3; MSRV 1.41+ ([#144])
- Bump `chacha20` crate dependency to v0.4 ([#159])
- Bump `poly1305` crate dependency to v0.6 ([#158])
[#159]: https://github.com/RustCrypto/AEADs/pull/159
[#158]: https://github.com/RustCrypto/AEADs/pull/158
[#144]: https://github.com/RustCrypto/AEADs/pull/144
> chacha20poly1305 v0.5.0

- Cargo.lock
- crypto_box/Cargo.toml
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
- Bump `aead` crate dependency to v0.3; MSRV 1.41+ ([#146])
- Bump `chacha20` crate dependency to v0.4 ([#159])
- Bump `poly1305` crate dependency to v0.6 ([#158])
[#159]: https://github.com/RustCrypto/AEADs/pull/159
[#158]: https://github.com/RustCrypto/AEADs/pull/158
[#146]: https://github.com/RustCrypto/AEADs/pull/146
> xsalsa20poly1305 v0.4.0

- Cargo.lock
- crypto_box/CHANGELOG.md
- crypto_box/Cargo.toml
- Bump `aead` crate dependency to v0.3; MSRV 1.41+ ([#146])
- Bump `xsalsa20poly1305` dependency to v0.4 ([#164])
[#146]: https://github.com/RustCrypto/AEADs/pull/146
[#164]: https://github.com/RustCrypto/AEADs/pull/164
> crypto_box v0.2.0

- aes-gcm/src/ctr.rs
- aes-gcm/src/lib.rs
Renames the generic parameters:
- `B` => `Aes` to reflect it should be instantiated with AES
- `N` => `NonceSize` which is consistent with the associated type name
> aes-gcm: use more descriptive generic parameter names

- Cargo.lock
- xsalsa20poly1305/Cargo.toml
- xsalsa20poly1305/src/lib.rs
Imports the type aliases added to the upstream `salsa20` crate.
Also adds some documentation improvements including `doc(cfg(...))`
> xsalsa20poly1305: add `Key` and `Nonce` type aliases + docs

- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/lib.rs
- chacha20poly1305/src/xchacha20poly1305.rs
Imports the type aliases added to the upstream `chacha20` crate.
> chacha20poly1305: add `Key` and `Nonce` type aliases

- Cargo.lock
- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- `Key`, `Nonce`, and `XNonce` type aliases ([#168])
[#168]: https://github.com/RustCrypto/AEADs/pull/168
> chacha20poly1305 v0.5.1

- Cargo.lock
- chacha20poly1305/src/lib.rs
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
- `Key` and `Nonce` type aliases + docs ([#167])
[#167]: https://github.com/RustCrypto/AEADs/pull/159
> xsalsa20poly1305 v0.4.1

- xsalsa20poly1305/src/lib.rs
For consistency with `NONCE_SIZE` and `TAG_SIZE`
> xsalsa20poly1305: add `KEY_SIZE` constant

- Cargo.lock
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
- `KEY_SIZE` constant ([#172])
[#172]: https://github.com/RustCrypto/AEADs/pull/172
> xsalsa20poly1305 v0.4.2

- crypto_box/src/lib.rs
This commit switches from importing the `aead` types through the re-export of the `aead` crate from the `xsalsa20poly1305` crate to importing them as `use xsalsa20poly1305::aead::*`.
The reason is https://docs.rs is not rendering the links to the `AeadInPlace::{encrypt_in_place, decrypt_in_place}` methods.
However, these links are rendering in all other AEAD crates besides this one, suggesting it's something this crate is doing differently from the others.
It's also possible that the reason is unlike the other AEAD crates, this one does not directly depend on `aead`, but accesses it vicariously through the `xsalsa20poly1305` crate. But we can cross that bridge when we get there if this doesn't fix the issue.
> crypto_box: tweak `aead` type imports

- Cargo.lock
- crypto_box/CHANGELOG.md
- crypto_box/Cargo.toml
- Bump `x25519-dalek` dependency to 1.0 ([#194])
[#194]: https://github.com/RustCrypto/AEADs/pull/194
> crypto_box v0.3.0

- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- ccm/Cargo.toml
- chacha20poly1305/Cargo.toml
- crypto_box/Cargo.toml
- eax/Cargo.toml
- mgm/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Disabled-by-default. Closes #204.
This mostly provides a `std::error::Error` impl on `aead::Error`.
> Add optional `std` feature to all crates

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- aes-siv/CHANGELOG.md
- aes-siv/Cargo.toml
- ccm/CHANGELOG.md
- ccm/Cargo.toml
- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- crypto_box/CHANGELOG.md
- crypto_box/Cargo.toml
- eax/CHANGELOG.md
- eax/Cargo.toml
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
Releases versions that are upgraded to use `block-cipher` v0.8 and `stream-cipher` v0.7.
- `aes-gcm` v0.7.0
- `aes-gcm-siv` v0.8.0
- `aes-siv` v0.4.0
- `ccm` v0.2.0
- `chacha20poly1305` v0.6.0
- `crypto_box` v0.4.0
- `eax` v0.2.0-pre (final release pending resolution of #214)
- `xsalsa20poly1305` v0.5.0
> Release new versions

- aes-gcm-siv/CHANGELOG.md
It appears I fat fingered the version number, releasing a v0.8.0 instead of a v0.6.0. Mea culpa.
Everything else about the release is consistent except CHANGELOG.md. This updates it to reflect what happened.
> aes-gcm-siv: fix CHANGELOG.md entries

- Cargo.lock
- eax/CHANGELOG.md
- eax/Cargo.toml
- API for online encryption/decryption ([#214])
- Optional `std` feature; disabled by default ([#217])
- Use `aead` crate; MSRV 1.41+
- Upgrade `aes` to v0.5, `block-cipher` to v0.8, `cmac` to v0.4, `ctr` to v0.5 ([#209])
[#217]: https://github.com/RustCrypto/AEADs/pull/217
[#214]: https://github.com/RustCrypto/AEADs/pull/214
[#209]: https://github.com/RustCrypto/AEADs/pull/209
> eax v0.2.0

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- aes-gcm/Cargo.toml
- aes-gcm/src/lib.rs
- aes-siv/Cargo.toml
- aes-siv/src/lib.rs
- aes-siv/src/siv.rs
- ccm/Cargo.toml
- ccm/src/lib.rs
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/cipher.rs
- chacha20poly1305/src/lib.rs
- chacha20poly1305/src/xchacha20poly1305.rs
- crypto_box/Cargo.toml
- eax/Cargo.toml
- eax/src/lib.rs
- eax/src/online.rs
- mgm/Cargo.toml
- mgm/src/lib.rs
- xsalsa20poly1305/Cargo.toml
- xsalsa20poly1305/src/lib.rs
...and updates associated dependencies:
- `aes` v0.6.0
- `ctr` v0.6.0
> Replace `block-cipher`/`stream-cipher` with `cipher` crate

- eax/src/lib.rs
- eax/src/online.rs
- eax/src/traits.rs
Implemented analogous to ccm by passing a second generic argument to
Eax.
Fixes #220.
This change should be mostly backwards compatible, apart from exporting the generic Tag instead of `pub type Tag = GenericArray<u8, U16>;`
It should be easy to make keep it completely backwards compatible if that’s better.
> eax: Allow variable tag length

- aes-gcm-siv/src/lib.rs
The implementation contained what's effectively a typo, albeit a harmless one.
It was trying to compute the size of a buffer to work on in parallel and was previously doing:
ParBlocks (8) * ParBlocks (8) = 64
Semantically what was intended was:
BlockSize (16) * ParBlocks (8) = 128
...which means the buffer was suboptimally sized for the underlying operation.
> aes-gcm-siv: fix interleaved buffer size

- .github/workflows/aes-gcm-siv.yml
- .github/workflows/aes-gcm.yml
- .github/workflows/aes-siv.yml
- Cargo.lock
- aes-gcm-siv/README.md
- aes-gcm/README.md
- aes-siv/README.md
- ccm/Cargo.toml
- eax/Cargo.toml
The `aes` crate is a key component of several crates in this repo, and just had an MSRV breaking change in RustCrypto/block-ciphers#216.
This commit bumps the MSRV of all crates in this repo which use the `aes` crate to MSRV 1.49+.
In the case of `aes-gcm` and `aes-gcm-siv` specifically, the changes in RustCrypto/universal-hashes#113 bumped the MSRV of `ghash` and `polyval` to 1.49+ as well, so there are multiple motivations for this new MSRV.
> Bump `aes` crate; `aes*` crates => MSRV 1.49+

- .github/workflows/aes-gcm-siv.yml
- .github/workflows/aes-gcm.yml
- .github/workflows/aes-siv.yml
- .github/workflows/chacha20poly1305.yml
- .github/workflows/crypto_box.yml
- .github/workflows/eax.yml
- .github/workflows/mgm.yml
- .github/workflows/xsalsa20poly1305.yml
- Cargo.lock
- chacha20poly1305/README.md
- chacha20poly1305/src/lib.rs
- crypto_box/README.md
Like we did with the `aes` crate in #252, this bumps the `chacha20` crate to a version which implements runtime CPU feature detection (AVX2/SSE2) and uses new support for `ManuallyDrop` union fields which became available in Rust 1.49.
> chacha20poly1305: bump `chacha20` crate; MSRV 1.49+

- Cargo.lock
- Cargo.toml
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- ccm/Cargo.toml
- chacha20poly1305/Cargo.toml
- eax/Cargo.toml
- mgm/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Release notes: https://github.com/RustCrypto/traits/pull/526
> Bump `aead` dependency to v0.4.0 release

- .cargo/audit.toml
Ignores the following advisories:
- RUSTSEC-2020-0145: heapless: UAF cloning a partially consumed iterator
- RUSTSEC-2020-0146: generic-array: lifetime extension in old versions
Re: RUSTSEC-2020-0145, the `aead` crate consumes the `heapless` crate this advisory is filed against, and does not iterate over `Vec`s nor does it clone them, so it should be unaffected.
Re: RUSTSEC-2020-0146, these are pulled in via `as-slice` which actually pulls in *three* versions of `generic-array`. Only the latest version is actually used (v0.14).
> .cargo/audit.toml: ignore `heapless` advisories

- .github/workflows/benches.yml
- .github/workflows/security-audit.yml
- Cargo.lock
- Cargo.toml
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- ccm/Cargo.toml
- eax/Cargo.toml
Release notes:
- `aes` v0.7.0: https://github.com/RustCrypto/block-ciphers/pull/238
- `ctr` v0.7.0: https://github.com/RustCrypto/stream-ciphers/pull/229
> Bump `aes` and `ctr` crate dependencies to v0.7

- Cargo.lock
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Wycheproof test vectors ([#274])
- Bump `aes` crate dependency to v0.7; MSRV 1.49+ ([#283])
- Bump `ctr` crate dependency to v0.7 ([#283])
- Bump `ghash` crate dependency to v0.4 ([#284])
[#274]: https://github.com/RustCrypto/AEADs/pull/274
[#284]: https://github.com/RustCrypto/AEADs/pull/284
> aes-gcm v0.9.0

- Cargo.lock
- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- crypto_box/Cargo.toml
- Wycheproof test vectors ([#274])
- `xchacha` feature name ([#257])
- MSRV 1.49+ ([#286], [#289])
- Bump `chacha20` crate dependency to v0.7 ([#286])
- Bump `poly1305` crate dependency to v0.7 ([#289])
[#257]: https://github.com/RustCrypto/AEADs/pull/257
[#274]: https://github.com/RustCrypto/AEADs/pull/274
[#286]: https://github.com/RustCrypto/AEADs/pull/286
[#289]: https://github.com/RustCrypto/AEADs/pull/289
> chacha20poly1305 v0.8.0

- Cargo.lock
- chacha20poly1305/CHANGELOG.md
- crypto_box/Cargo.toml
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
- MSRV 1.49+ ([#286], [#289])
- Bump `chacha20` crate dependency to v0.7 ([#286])
- Bump `poly1305` crate dependency to v0.7 ([#289])
[#286]: https://github.com/RustCrypto/AEADs/pull/286
[#289]: https://github.com/RustCrypto/AEADs/pull/289
> xsalsa20poly1305 v0.7.0

- Cargo.lock
- ccm/CHANGELOG.md
- ccm/Cargo.toml
- Bump `aead` dependency to v0.4 ([#270])
- Bump `cipher` dependency to v0.3 ([#283])
- Panic on 32-bit targets ([#263])
[#263]: https://github.com/RustCrypto/AEADs/pull/263
> ccm v0.4.0

- Cargo.lock
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
- Bump `rand_core` crate dependency to v0.6 ([#292])
[#292]: https://github.com/RustCrypto/AEADs/pull/292
> xsalsa20poly1305 v0.7.1

- Cargo.lock
- crypto_box/CHANGELOG.md
- crypto_box/Cargo.toml
- Bump `chacha20poly1305` crate dependency to v0.8 ([#290])
- Bump `xsalsa20poly1305` crate dependency to v0.7 ([#291])
- Bump `rand_core` crate dependency to v0.6 ([#292])
- Fix XChaCha20Poly1305 key derivation ([#295])
[#290]: https://github.com/RustCrypto/AEADs/pull/290
[#291]: https://github.com/RustCrypto/AEADs/pull/291
[#292]: https://github.com/RustCrypto/AEADs/pull/292
[#295]: https://github.com/RustCrypto/AEADs/pull/295
> crypto_box v0.6.0

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- Wycheproof test vectors ([#274])
- Bump `aes` and `ctr` crate dependencies to v0.7 ([#283])
- Bump `polyval` to v0.5 ([#284])
- Interleaved buffer size ([#235])
[#235]: https://github.com/RustCrypto/AEADs/pull/235
[#274]: https://github.com/RustCrypto/AEADs/pull/274
[#284]: https://github.com/RustCrypto/AEADs/pull/284
> aes-gcm-siv v0.10.0

- Cargo.lock
- aes-siv/CHANGELOG.md
- aes-siv/Cargo.toml
- AES-SIV-CMAC Wycheproof test vectors ([#276])
- Bump `aes` and `ctr` crate dependencies to v0.7 ([#283])
- Bump `cmac` and `pmac` deps to v0.6 releases ([#285])
[#276]: https://github.com/RustCrypto/AEADs/pull/276
[#285]: https://github.com/RustCrypto/AEADs/pull/285
> aes-siv v0.6.0

- Cargo.lock
- eax/CHANGELOG.md
- eax/Cargo.toml
- Allow variable tag length ([#231])
- Bump `aes` and `ctr` crate dependencies to v0.7 ([#283])
- Bump `cmac` and `pmac` deps to v0.6 releases ([#285])
[#231]: https://github.com/RustCrypto/AEADs/pull/231
[#285]: https://github.com/RustCrypto/AEADs/pull/285
> eax v0.4.0

- Cargo.lock
- mgm/CHANGELOG.md
- mgm/Cargo.toml
- Bump `aead` dependency to v0.4.0 release ([#270])
> mgm v0.4.0

- Cargo.lock
- aes-gcm/Cargo.toml
Adds a `force-soft` crate feature which in turn enables the corresponding `aes/force-soft` and `ghash/force-soft` features.
This enables operation on Rust 1.41+.
> aes-gcm: add `force-soft` feature

- Cargo.lock
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- `force-soft` feature ([#305])
[#305]: https://github.com/RustCrypto/AEADs/pull/305
> aes-gcm v0.9.1

- xsalsa20poly1305/Cargo.toml
Currently it's not enabled by default even though rand_core dependency
is enabled by default.
> Add aead/rand_core to default features to xsalsa20poly1305.

- mgm/CHANGELOG.md
- mgm/Cargo.toml
- mgm/src/lib.rs
This change allows us to work with `Mgm<&'a BlockCipher>`.
> mgm: remove unnecessary NewBlockCipher bounds

- crypto_box/src/lib.rs
It's convenient to have PublicKey as key in a Map (for isntance, we [use it in tox](https://github.com/tox-rs/tox/blob/db7de02c6d699b03c014c8bc11d63101022cfbc4/tox_core/src/relay/client/connections.rs#L102)).
> Implement hash for PublicKey.

- chacha20poly1305/Cargo.toml
Adds a `force-soft` feature which forces non-SSE implementations for the `chacha20` and `poly1305` crates.
Follows the same pattern as #305.
> chacha20poly1305: Add `force-soft` feature

- Cargo.lock
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Nightly-only `armv8` feature ([#318])
[#318]: https://github.com/RustCrypto/AEADs/pull/318
> aes-gcm v0.9.2

- aes-siv/Cargo.toml
This change exposes a feature to enable users to use AES-PMAC-SIV constructs.
Unfortunately it renamed the "pmac" feature because it conflicts with the pmac dependency.
> AesPmacSiv features were not selectable by end users

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- aes-siv/Cargo.toml
- Nightly-only `armv8` feature ([#318])
[#318]: https://github.com/RustCrypto/AEADs/pull/318
> aes-gcm-siv v0.10.1

- Cargo.lock
- aes-siv/CHANGELOG.md
- aes-siv/Cargo.toml
- aes-siv/src/lib.rs
- aes-siv/src/siv.rs
- `pmac` crate feature ([#321])
[#321]: https://github.com/RustCrypto/AEADs/pull/321
> aes-siv v0.6.1

- Cargo.lock
- ccm/CHANGELOG.md
- ccm/Cargo.toml
- ccm/src/lib.rs
Closes #178
Also includes minor improvements of the CBC-MAC computation and adds `From<BlockCipher>` and `Clone` impls.
> ccm: use the ctr crate for encryption and decryption

- Cargo.lock
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
The crates have MSRV 1.49, which is higher than the `hex-literal`'s MSRV.
> Bump hex-literal to v0.3 for aes-gcm and aes-siv

- README.md
I think MSRV information is more valuable than the build badges, especially considering that in this repository we have crates with 3 different MSRVs.
Also I've removed the `aes-ccm` mention, since the `ccm` crate should be preferred for now. Later we probably should introduce a folder with crates containing common common composition of primitives (AES-GCM, ChaCha20Poly1305, etc.).
> README: replace build badges column with MSRV

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- aes-siv/CHANGELOG.md
- aes-siv/Cargo.toml
- ccm/CHANGELOG.md
- ccm/Cargo.toml
- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- crypto_box/CHANGELOG.md
- crypto_box/Cargo.toml
- deoxys/CHANGELOG.md
- deoxys/Cargo.toml
- eax/CHANGELOG.md
- eax/Cargo.toml
- mgm/CHANGELOG.md
- mgm/Cargo.toml
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
`zeroize` in v1.4 has updated its MSRV to 1.51 breaking our MSRV promise. This PR pins its version to v1.3.x. `subtle` is also preemptively pinned to v2.4.
> Pin zeroize dependency to v1.3 and subtle to v2.4

- Cargo.lock
- mgm/CHANGELOG.md
- mgm/Cargo.toml
- mgm/src/lib.rs
It results in two-pass decryption which may be a bit less performant than the current approach, but should be a bit more secure in some contexts.
> mgm: decrypt only after tag verification

- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- ccm/Cargo.toml
- chacha20poly1305/Cargo.toml
- deoxys/Cargo.toml
- eax/Cargo.toml
- mgm/Cargo.toml
- xsalsa20poly1305/Cargo.toml
The version was pinned to `subtle` 2.4.x and `zeroize` 1.3.x to prevent MSRV breakages, but these crates are comaptible with any version before that as well.
This commit loosens the restrictions to allow compatibility with earlier versions of these crates too. This permits a wider range of combinations.
> Relax `subtle` and `zeroize` requirements

- Cargo.lock
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
> aes-gcm v0.9.4

- Cargo.lock
- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
> chacha20poly1305 v0.8.2

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
> aes-gcm-siv v0.10.3

- .github/workflows/chacha20poly1305.yml
- Cargo.lock
- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- chacha20poly1305/README.md
- chacha20poly1305/src/lib.rs
- chacha20poly1305/tests/lib.rs
Bumps `chacha20` to the latest release, which has the following
additional changes:
- `chacha20` is now a hard dependency, now that the main use case for making it optional, using `c2-chacha` instead of `chacha20`, is irrelevant in that the performance difference has been eliminated.
- The `xchacha20` feature has been removed making the `XChaCha*` types always available.
- The `chacha20-reduced-round` and `xchacha20-reduced-round` features have been coalesced into a single `reduced-round` feature.
> chacha20poly1305: bump `chacha20` to v0.9; MSRV 1.51

- Cargo.lock
- xsalsa20poly1305/Cargo.toml
This release removed the `xsalsa20` feature, and always includes it.
> xsalsa20poly1305: bump `salsa20` dependency to v0.9

- Cargo.lock
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
- Bump `salsa20` dependency to v0.9 ([#366])
[#366]: https://github.com/RustCrypto/AEADs/pull/366
> xsalsa20poly1305 v0.7.3

- Cargo.lock
- chacha20poly1305/Cargo.toml
This release includes an updated `chacha20` v0.9 dependency which removes the previous `zeroize` version pinning, and should unblock people who are having `zeroize` version compatibility issues
> chacha20poly1305 v0.10.0-pre

- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- ccm/Cargo.toml
- deoxys/Cargo.toml
- eax/Cargo.toml
- mgm/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Version pinning to preserve MSRV has proven to be problematic, in that it prevents compatible combinations of crates from working due to artificial restrictions intended to preserve out-of-the-box nameplate MSRV on particular crates.
Since we're bumping MSRV in these crates anyway as part of the `cipher` upgrade, this commit removes these restrictions, which should allow more compatible combinations of crates to work.
> Remove `subtle` pinning

- .github/workflows/ccm.yml
- Cargo.lock
- ccm/Cargo.toml
- ccm/README.md
- ccm/src/lib.rs
```
* bump cipher and ctr dependencies to use it with the latest aes crate.
Fix version difference.
* bump hex-literal.
* change MSRV to 1.56.0.
* remove separate job "heapless" in github workflow.
```
> ccm: update dependencies

- ccm/src/lib.rs
`U12` is listed twice for the tag size. The last constant should be `U16`.
> Fix typo U12 -> U16

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- ccm/Cargo.toml
- chacha20poly1305/Cargo.toml
- deoxys/Cargo.toml
- eax/Cargo.toml
- mgm/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Cuts prereleases of all crates with an updated `aead` dependency
> Prereleases with `aead` v0.5 prerelease

- chacha20poly1305/CHANGELOG.md
Adds release notes for a v0.9.1 release of `chacha20poly1305` (done on a separate branch since `master` is curently v0.10.0-pre.1)
This release unpins `zeroize`, allowing any version to be used. It was pinned to prevent MSRV breakages, however this has proven to be quite problematic and prevents compatible versions of crates from being used.
> chacha20poly1305: add v0.9.1 release notes

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- aes-gcm/Cargo.toml
- aes-gcm/src/lib.rs
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/cipher.rs
Upgrades the following UHF crates:
- `ghash` v0.5.0-pre.1
- `poly13095` v0.8.0-pre.1
- `polyval` v0.6.0-pre.1
> Bump UHF crates to `universal-hash` v0.5.0-pre.1 prereleases

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- chacha20poly1305/Cargo.toml
- xsalsa20poly1305/Cargo.toml
These prereleases use updated universal hash implementations based on `universal-hash` v0.5.0-pre.1.
See #439, #440
> Cut `-pre.2` releases of crates which use UHFs

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- ccm/Cargo.toml
- chacha20poly1305/Cargo.toml
- deoxys/Cargo.toml
- eax/Cargo.toml
- mgm/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Release PR: https://github.com/RustCrypto/traits/pull/1058
> Bump `aead` crate dependency to v0.5

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- chacha20poly1305/Cargo.toml
- xsalsa20poly1305/Cargo.toml
Upgrades the following UHF crates:
- `ghash` v0.5.0-pre.2
- `poly13095` v0.8.0-pre.2
- `polyval` v0.6.0-pre.2
> Bump UHF crates to `universal-hash` v0.5.0-pre.2 prereleases

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- aes-gcm-siv/tests/aes128gcmsiv.rs
- aes-gcm-siv/tests/aes256gcmsiv.rs
- aes-gcm/Cargo.toml
- aes-gcm/src/lib.rs
- aes-gcm/tests/aes128gcm.rs
- aes-gcm/tests/aes256gcm.rs
- aes-gcm/tests/other_ivlen.rs
- aes-siv/Cargo.toml
- aes-siv/src/lib.rs
- ccm/Cargo.toml
- ccm/src/lib.rs
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/lib.rs
- deoxys/Cargo.toml
- deoxys/src/lib.rs
- eax/Cargo.toml
- eax/src/lib.rs
- mgm/Cargo.toml
- mgm/src/lib.rs
- xsalsa20poly1305/Cargo.toml
- xsalsa20poly1305/src/lib.rs
The `getrandom` feature transitively activates `aead/getrandom` and makes `aead::OsRng` available.
RNG access is pretty essential for successful use of these crates. It's needed to generate random keys as the very least.
The documentation has also been updated to show the generation of random keys, as opposed to using a hardcoded one.
> Enable `getrandom` feature by defaut; improve docs

- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/lib.rs
The zeroize-on-drop code was present before, but this PR announces that explicitly in the public API.
Some notes:
- To keep changes to the minimum, I did not add a `Zeroize` impl (probably not a good idea anyway)
- Had to restrict `zeroize` to `>=1.5`, hopefully that's ok.
> Make `ChaChaPoly1305` implement `ZeroizeOnDrop`

- Cargo.lock
- aes-siv/CHANGELOG.md
- aes-siv/Cargo.toml
- Relax `zeroize` requirement to `^1` ([#360], [#401])
- Bump `aes` crate to v0.8 ([#431])
- Bump `aead` crate dependency to v0.5 ([#444])
[#401]: https://github.com/RustCrypto/AEADs/pull/401
[#431]: https://github.com/RustCrypto/AEADs/pull/431
> aes-siv v0.7.0

- Cargo.lock
- ccm/CHANGELOG.md
- ccm/Cargo.toml
- Relax `zeroize` requirement to `^1` ([#360])
- Bump `ctr`, `cipher`, annd `hex-literal` dependencies ([#432])
- Bump `aead` crate dependency to v0.5 ([#444])
- `subtle` pinning ([#408])
[#408]: https://github.com/RustCrypto/AEADs/pull/408
[#432]: https://github.com/RustCrypto/AEADs/pull/432
> ccm v0.5.0

- Cargo.lock
- deoxys/CHANGELOG.md
- deoxys/Cargo.toml
- Bump `aead` crate dependency to v0.5 ([#444])
- Bump `aes` dependency to v0.8 ([#450])
[#450]: https://github.com/RustCrypto/AEADs/pull/450
> deoxys v0.1.0

- Cargo.lock
- eax/CHANGELOG.md
- eax/Cargo.toml
- eax/src/lib.rs
- Bump `aead` crate dependency to v0.5 ([#444])
- Bump `cipher` to v0.4 ([#451])
[#451]: https://github.com/RustCrypto/AEADs/pull/451
> eax v0.5.0

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- chacha20poly1305/Cargo.toml
- xsalsa20poly1305/Cargo.toml
The final releases of these crates are out, and this commit bumps their dependency versions:
- `ghash` v0.5
- `polyval` v0.6
- `poly1305` v0.8
> Bump UHF crates to `universal-hash` v0.5-based releases

- aes-gcm-siv/README.md
- aes-gcm/README.md
- aes-siv/README.md
- ccm/README.md
- chacha20poly1305/README.md
- deoxys/README.md
- eax/README.md
- mgm/README.md
- xsalsa20poly1305/README.md
These badges include download numbers, eliminating the need to have a separate badge to track download counts
> README.md(s): use crate badges from buildstats.info

- Cargo.lock
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Bump `aes` dependency to v0.8 ([#409])
- Bump `aead` dependency to v0.5 ([#444])
- Bump `ghash` dependency to v0.5 ([#454])
[#409]: https://github.com/RustCrypto/AEADs/pull/409
[#454]: https://github.com/RustCrypto/AEADs/pull/454
> aes-gcm v0.10.0

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- aes-gcm/CHANGELOG.md
- Bump `aead` dependency to v0.5 ([#444])
- Bump `polyval` dependency to v0.6 ([#454])
[#454]: https://github.com/RustCrypto/AEADs/pull/454
> aes-gcm-siv v0.11.0

- Cargo.lock
- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- Impl `ZeroizeOnDrop` for `ChaChaPoly1305` ([#447])
- Bump `chacha20` to v0.9 ([#402])
- Bump `aead` dependency to v0.5 ([#444])
- Bump `poly1305` dependency to v0.8 ([#454])
[#402]: https://github.com/RustCrypto/AEADs/pull/402
[#447]: https://github.com/RustCrypto/AEADs/pull/447
[#454]: https://github.com/RustCrypto/AEADs/pull/454
> chacha20poly1305 v0.10.0

- Cargo.lock
- chacha20poly1305/CHANGELOG.md
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
- Bump `salsa20` dependency to v0.10 ([#402])
- Bump `aead` dependency to v0.5 ([#444])
- Bump `poly1305` dependency to v0.8 ([#454])
[#402]: https://github.com/RustCrypto/AEADs/pull/402
[#447]: https://github.com/RustCrypto/AEADs/pull/447
[#454]: https://github.com/RustCrypto/AEADs/pull/454
> xsalsa20poly1305 v0.9.0

- aes-gcm-siv/README.md
- aes-gcm-siv/src/lib.rs
The links weren't rendering correctly.
This commit shifts to including the README.md in the rustdoc. The rustdoc was previously copy/paste of the README.md. This has the effect of fixing the links.
> aes-gcm-siv: fix rustdoc documentation

- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- aes-gcm/src/lib.rs
- aes-siv/src/lib.rs
- ccm/src/lib.rs
- chacha20poly1305/src/lib.rs
- deoxys/src/lib.rs
- eax/src/lib.rs
- mgm/src/lib.rs
- xsalsa20poly1305/src/lib.rs
The rustdocs all contained copy-paste of the README.mds, often out of date or with typos, which this commit corrects.
> Include README.md in rustdoc

- Cargo.lock
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- rustdoc typos and formatting ([#461], [#462])
[#461]: https://github.com/RustCrypto/AEADs/pull/461
[#462]: https://github.com/RustCrypto/AEADs/pull/462
> aes-gcm v0.10.1

- Cargo.lock
- aes-gcm-siv/CHANGELOG.md
- aes-gcm-siv/Cargo.toml
- rustdoc typos and formatting ([#460], [#461], [#462])
[#460]: https://github.com/RustCrypto/AEADs/pull/460
[#461]: https://github.com/RustCrypto/AEADs/pull/461
[#462]: https://github.com/RustCrypto/AEADs/pull/462
> aes-gcm-siv v0.11.1

- Cargo.lock
- aes-gcm-siv/src/lib.rs
- aes-gcm/src/lib.rs
- aes-siv/src/lib.rs
- ccm/src/lib.rs
- chacha20poly1305/src/lib.rs
- deoxys/src/lib.rs
- eax/src/lib.rs
- xsalsa20poly1305/src/lib.rs
This provides a better example closer to real-world code.
See: https://docs.rs/aead/0.5.1/aead/trait.AeadCore.html#method.generate_nonce
> Use `AeadCore::generate_nonce` in rustdoc examples

- Cargo.lock
- chacha20poly1305/CHANGELOG.md
- chacha20poly1305/Cargo.toml
- `rand_core` feature ([#467])
[#467]: https://github.com/RustCrypto/AEADs/pull/467
> chacha20poly1305 v0.10.1

- chacha20poly1305/src/lib.rs
Currently at https://docs.rs/chacha20poly1305/latest/chacha20poly1305/#supported-algorithms it renders link to audit from <https://github.com/RustCrypto/AEADs/blob/57956bf2d8273e7b3fddd127aa7116ad5ef1c5ad/chacha20poly1305/README.md?plain=1#L82>.
> Add correct link to Too much crypto

- aes-gcm/src/lib.rs
Fix a small typo in `aes-gcm/src/lib.rs`.
> Fix a typo

- .github/workflows/aes-gcm-siv.yml
- .github/workflows/aes-gcm.yml
- .github/workflows/aes-siv.yml
- .github/workflows/benches.yml
- .github/workflows/ccm.yml
- .github/workflows/chacha20poly1305.yml
- .github/workflows/deoxys.yml
- .github/workflows/eax.yml
- .github/workflows/mgm.yml
- .github/workflows/workspace.yml
- .github/workflows/xsalsa20poly1305.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/RustCrypto/AEADs/actions/runs/4294813272:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain).
> Replace unmaintained actions-rs/toolchain action in CI workflows

- benches/Cargo.toml
- benches/src/aes-gcm-siv.rs
- benches/src/aes-gcm.rs
- benches/src/chacha20poly1305.rs
- benches/src/deoxys.rs
- benches/src/eax.rs
This also bumps the versions of `criterion`, `aes` and `criterion-cycles-per-byte`.
I'm not sure how verbose I should've been with the `cfg`s, let me know if there's a preferred style and I'd be happy to change them!
> benches: only use criterion CPB measurements on x86_64 and x86 targets

- benches/Cargo.toml
- benches/src/aes-gcm-siv.rs
- benches/src/aes-gcm.rs
- benches/src/chacha20poly1305.rs
- benches/src/deoxys.rs
- benches/src/eax.rs
I must apologize - it appears my PR from the other day (#515) broke benchmarks on `x86_64` and `x86`.
I didn't realize as I was developing on `Aarch64`, but I'm not too sure why CI didn't pick it up.
The benchmark crate also refused to compile due to the `ascon-aead` benches - they attempt to use `rand` as a dependency but it wasn't specified.
> benches: fix compilation

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- aes-gcm/Cargo.toml
- aes-gcm/src/lib.rs
- aes-siv/Cargo.toml
- aes-siv/src/lib.rs
- ccm/Cargo.toml
- chacha20poly1305/Cargo.toml
- chacha20poly1305/src/lib.rs
- deoxys/Cargo.toml
- deoxys/src/lib.rs
- eax/Cargo.toml
- eax/src/lib.rs
- mgm/Cargo.toml
- xsalsa20poly1305/Cargo.toml
- xsalsa20poly1305/src/lib.rs
Added support for `arrayvec::ArrayVec` as per changes in https://github.com/RustCrypto/traits/pull/1219. Marked as draft for now until a new release of `aead` is published.
> ArrayVec support

- xsalsa20poly1305/Cargo.toml
- xsalsa20poly1305/README.md
The `crypto_secretbox` crate is forked from `xsalsa20poly1305`, but modified and expanded to support the libsodium flavor of XChaCha20Poly1305 in addition to XSalsa20Poly1305.
Further updates will happen on `crypto_secretbox`:
https://github.com/RustCrypto/nacl-compat/tree/master/crypto_secretbox
> xsalsa20poly1305: deprecate in favor of `crypto_secretbox`

- Cargo.lock
- xsalsa20poly1305/CHANGELOG.md
- xsalsa20poly1305/Cargo.toml
Deprecate `xsalsa20poly1305` in favor of `crypto_secretbox` ([#525])
[#525]: https://github.com/RustCrypto/AEADs/pull/525
> xsalsa20poly1305 v0.9.1

- .cargo/audit.toml
- Cargo.lock
We're getting flagged for our own `xsalsa20poly1305` crate.
Also bumps `spin` to a non-vulnerable version.
> CI: fix security audit

- Cargo.lock
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- `rand_core` feature to all crates ([#467])
- Support for partial tag sizes ([#501])
- `ArrayVec` support ([#503])
[#467]: https://github.com/RustCrypto/AEADs/pull/467
[#501]: https://github.com/RustCrypto/AEADs/pull/501
[#503]: https://github.com/RustCrypto/AEADs/pull/503
> aes-gcm v0.10.2

- aes-siv/src/lib.rs
- chacha20poly1305/src/cipher.rs
- xsalsa20poly1305/src/lib.rs
Fixes warnings on `clippy::needless_borrow` and `clippy::explicit_auto_deref`.
> Fix `clippy::needless_borrow` and `clippy::explicit_auto_deref`

- aes-gcm/src/lib.rs
- aes-gcm/tests/aes128gcm.rs
- aes-gcm/tests/aes256gcm.rs
- aes-gcm/tests/common/mod.rs
In #409, for whatever reason I moved the application of the keystream from after the tag check to before. This means the keystream is applied unilaterally, instead of only when tag verification is successful.
Sadly, there was a TODO to test for this. A test has been added to ensure the buffer is unmodified on tag verification failure. It was red/green tested to ensure it caught the previous bug, and that the fix corrects it.
This is being tracked as GHSA-423w-p2w9-r7vq (currently embargoed).
> aes-gcm: avoid exposing plaintext on tag verification failure

- Cargo.lock
- aes-gcm/CHANGELOG.md
- aes-gcm/Cargo.toml
- Avoid exposing plaintext on tag verification failure ([#551])
[#551]: https://github.com/RustCrypto/AEADs/pull/551
> aes-gcm v0.10.3

- aes-siv/src/lib.rs
add compile time NonceSize, #496
> feat(aes-siv): generic nonce sizes for SivAead

- Cargo.lock
- ascon-aead/Cargo.toml
- ascon-aead/src/lib.rs
Not zeroizing the state may expose the private key.
As the MSRV is below 1.60 the `dep:` syntax is not available. Hence, the second feature `sponge-zeroize`. Any other suggestions to handle it better are welcome.
This relies on https://github.com/RustCrypto/sponges/pull/57 and a new release of the `ascon` crate.
> ascon-aead: Add ascon sponge Zeroize feature

- Cargo.toml
Gets rid of the warning:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
Also prevents spurious feature activation between dependencies/dev-dependencies/build-dependencies
> Cargo.toml: enable `resolver = "2"`

- Cargo.lock
- ocb3/README.md
- ocb3/src/lib.rs
- ocb3/tests/kats.rs
Renames `AesOcb3` to `Ocb3`.
Unlike AES-GCM, AES-GCM-SIV, and AES-SIV, in which AES is the de facto cipher for that mode, OCB is defined in a more cipher-agnostic way similar to CCM or EAX modes (which, as it were, is reflected in our choice of crate names).
This renames the type to reflect that, and as it were, match the crate name as well.
> ocb3: use `Ocb3` as the type name

- ccm/README.md
This adds a mention of AES-CCM in CCM's README as an example.
AES-CCM is the most prominent use case of CCM, as evidenced by the wikipedia articles both of CCM and its users always listing that combination.
Practically, this ensures that users looking for `aes-ccm` at crates.io find this, especially if https://github.com/martindisch/aes-ccm/issues/9 is not followed up on. (Concrete example: I was a few steps short of starting to update the aes-ccm crate to recent traits when I found that issue which pointed me here; the present fix would have spared me that detour).
> ccm: Mention AES-CCM in README

- ocb3/README.md
- ocb3/src/lib.rs
Based on the recommendations of the following paper, which describes an attack against OCB3 mode:
https://eprint.iacr.org/2023/326.pdf
> In the case of OCB3, it is easy to fix the algorithm’s specification
> in order to avoid the weakness and abide to the full assumptions of
> the security proof. If the description is unchanged, the requirement
> N ≥ 6 must become an absolute requirement.
Furthermore, this restricts the minimum tag size to 1-byte, up from the former 0-bytes. This is a questionable choice of minimum but reflects the wording in the RFC:
> The TAGLEN parameter specifies the length of authentication tag used
> by OCB and may be any value up to 128
Closes #592
> ocb3: restrict minimum `NonceSize` to `U6`

- ocb3/README.md
- ocb3/src/lib.rs
Also adds `compile_fail` tests to check that the sizes are correctly enforced at compile time.
The first commit intentionally does not include the fix to demonstrate that `NonZero` bounds are necessary.
> ocb3: fix nonce and tag size bounds

- aes-gcm-siv/src/lib.rs
added to ensure consistency with it's sister `aes-gcm` crate, which also re-exports `aes` ([aes-gcm/src/lib.rs:114](https://github.com/gstand/AEADs/blob/master/aes-gcm/src/lib.rs#L114)).
finds specific use in defining a `Key` generic for example; it takes a `KeySizeUser` which are a majority `Aes*` structs from `aes`, such as: `Key<Aes256>`. 
this change allows the consumer to just reference the re-export as opposed to pulling in the entire `aes` crate to their own crate. i was pivoting from `aes-gcm` to `aes-gcm-siv` myself when i came across this and took it upon myself to smooth out the discrepancy.
> feat(aes-gcm-siv): re-export `aes` crate

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- chacha20poly1305/Cargo.toml
Cuts the following prerelease versions:
- `aes-gcm` v0.11.0-pre.1
- `aes-gcm-siv` v0.12.0-pre.1
- `chacha20poly1305` v0.11.0-pre.1
> Cut pre.1 prereleases

- .github/workflows/aead-stream.yml
- Cargo.lock
- Cargo.toml
- README.md
- aead-stream/CHANGELOG.md
- aead-stream/Cargo.toml
- aead-stream/LICENSE-APACHE
- aead-stream/LICENSE-MIT
- aead-stream/README.md
- aead-stream/src/lib.rs
This PR extracts implementation of the STREAM construction from the `aead` crate into a separate crate as was proposed in https://github.com/RustCrypto/traits/issues/1665.
> aead-stream: extract implementation from the aead crate

- .github/workflows/aes-gcm-siv.yml
- .github/workflows/aes-gcm.yml
- Cargo.lock
- Cargo.toml
- aes-gcm-siv/Cargo.toml
- aes-gcm-siv/src/lib.rs
- aes-gcm/Cargo.toml
- aes-gcm/src/lib.rs
- aes-siv/Cargo.toml
- aes-siv/src/lib.rs
- aes-siv/src/siv.rs
- ccm/Cargo.toml
- ccm/src/lib.rs
- chacha20poly1305/Cargo.toml
- deoxys/Cargo.toml
- eax/Cargo.toml
- eax/src/lib.rs
- eax/src/online.rs
- ocb3/Cargo.toml
- ocb3/src/lib.rs
- aes 0.9.0-pre.1 -> 0.9.0-pre.2
- cipher 0.5.0-pre.6 -> 0.5.0-pre.7
- cmac 0.8.0-pre.1 -> 0.8.0-pre.2
- pmac 0.8.0-pre.1 -> 0.8.0-pre.2
> bump [aes, cipher, pmac, cmac] dependencies

- Cargo.lock
- Cargo.toml
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- chacha20poly1305/Cargo.toml
Cuts the following prerelease versions:
- `aes-gcm` v0.11.0-pre.2
- `aes-gcm-siv` v0.12.0-pre.2
- `aes-siv` v0.8.0-pre.2
- `chacha20poly1305` v0.11.0-pre.2
> Cut pre.2 prereleases

- aead-stream/src/lib.rs
I believe that we the `StreamPrimitive` for `StreamLE31` in the library is not using the correct value for `COUNTER_MAX`, choosing `0x0FFF_FFFF` rather than `0x7FFF_FFFF`, resulting in a reduced space for the message counter. This commit changes the value to use the full range.
I do not believe this is a security issue, but it does reduce the functionality of the library.
Let me know if my understanding of the problem is incorrect or if I'm attempting to commit this to the wrong library.
> Use full range of the stream counter for StreamLE31

- .github/workflows/benches.yml
- benches/Cargo.toml
- benches/src/ascon-aead.rs
Also fix benches CI job and tweak ascon-aead benchmarks to make them more consistent with other benchmarks.
Closes #549
> benches: fix compilation errors

- aead-stream/Cargo.toml
- aead-stream/src/lib.rs
This PR follows removal of the items from `aead` in https://github.com/RustCrypto/traits/pull/1713
In a future PR I plan to refactor `aead-stream` further, so it's convenient to have all code in one place.
> aead-stream: move the remaining items from `aead`

- mgm/Cargo.lock
This should fix the CI failure caused by compiler warning.
> mgm: update Cargo.lock

- ascon-aead/src/asconcore.rs
- ascon-aead/src/lib.rs
We generally do not include license headers in source files and rely solely on the LICENSE files instead.
> ascon-aead: remove license headers from source files

- ascon-aead/src/asconcore.rs
- ascon-aead/src/lib.rs
This reverts commit aafc20ed4af21c7c2246e10ce80147a5ad1196d5.
See discussion on #676
> Revert "ascon-aead: remove license headers from source files (#676)"

- Cargo.lock
- deoxys/Cargo.toml
- deoxys/src/lib.rs
- deoxys/src/modes.rs
This is to prepare the migration to `AeadInOut`, following https://github.com/RustCrypto/traits/pull/1793
Note: there is a strong chance this could actually use the StreamCipherCore api, but I couldn't not make it fit.
> deoxys: rewrite the internals to use inout

- deoxys/src/modes.rs
The change reduces code drift to the right and simplifies the branching structure.
It was previously suggested [here](https://github.com/RustCrypto/AEADs/pull/666#discussion_r2009532388).
> deoxys: tweak `DeoxysMode::encrypt/decrypt_inout` methods

- README.md
With migration to the 2024 edition we have relaxed our MSRV policy.
> Remove the MSRV policy section from the root README

- Cargo.lock
- Cargo.toml
- ocb3/Cargo.toml
- ocb3/src/lib.rs
This is to prepare the migration to `AeadInOut`, following https://github.com/RustCrypto/traits/pull/1793
Depends:
- https://github.com/RustCrypto/utils/pull/1170
> ocb3: migrate internals to use inout

- Cargo.lock
- Cargo.toml
- aead-stream/Cargo.toml
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- ascon-aead128/Cargo.toml
- belt-dwp/Cargo.toml
- ccm/Cargo.toml
- chacha20poly1305/Cargo.toml
- deoxys/Cargo.toml
- eax/Cargo.toml
- ocb3/Cargo.toml
- xaes-256-gcm/Cargo.toml
Also bumps previously released crates to `rc.0` and bumps version and adds `-pre` to crates with breaking changes which didn't get properly bumped before
> Bump `cipher` dependency to v0.5.0-rc.0

- aes-siv/src/siv.rs
It's confusing, and end users should use `KeySizeUser`.
Closes #700
> aes-siv: remove `siv::KeySize` alias from public API

- Cargo.lock
- Cargo.toml
- aes-siv/Cargo.toml
- ocb3/Cargo.toml
- ocb3/src/lib.rs
@newpavlov what's the replacement for `StreamCipherCoreWrapper::from_core`?
```
error[E0599]: no function or associated item named `from_core` found for struct `StreamCipherCoreWrapper` in the current scope
--> ccm/src/lib.rs:265:36
|
265 | ...let mut ctr = Ctr32BE::from_core(CtrCore::inner_iv_init(&self.ciph...
|                           ^^^^^^^^^ function or associated item not found in `StreamCipherCoreWrapper<CtrCore<_, Ctr32BE>>`
```
> Bump `hybrid-array` to v0.4

- Cargo.lock
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- benches/Cargo.toml
- benches/src/ascon-aead128.rs
- chacha20poly1305/Cargo.toml
Uses `hybrid-array` v0.4-compatible versions
> Bump universal hashes

- Cargo.lock
- aead-stream/Cargo.toml
- aes-gcm-siv/Cargo.toml
- aes-gcm/Cargo.toml
- aes-siv/Cargo.toml
- chacha20poly1305/Cargo.toml
- ocb3/Cargo.toml
- xaes-256-gcm/Cargo.toml
Releases the following:
- `aead-stream` v0.6.0-rc.1
- `aes-gcm` v0.11.0-rc.1
- `aes-gcm-siv` v0.12.0-rc.1
- `aes-siv` v0.8.0-rc.1
- `chacha20poly1305` v0.11.0-rc.1
- `xaes-256-gcm` v0.1.0-rc.1
> Cut prereleases with `hybrid-array` v0.4 support
