RustCrypto/AEADs

chacha20poly1305/CHANGELOG.md, chacha20poly1305/Cargo.toml
=> chacha20poly1305 v0.1.0

chacha20poly1305/Cargo.toml, chacha20poly1305/src/cipher.rs
This is the first release of the `polyval` crate that uses the new `UniversalHash` trait.
=> chacha20poly1305: Upgrade to `polyval` v0.4.0

chacha20poly1305/CHANGELOG.md, chacha20poly1305/Cargo.toml
- Update to `poly1305` v0.4 ([#8])
[#8]: https://github.com/RustCrypto/AEADs/pull/8
=> chacha20poly1305 v0.1.1

aes-gcm-siv/Cargo.toml, aes-gcm-siv/benches/aes-gcm-siv.rs
=> add criterion benchmark for aes-gcm-siv

aes-gcm-siv/CHANGELOG.md, aes-gcm-siv/Cargo.toml, aes-gcm-siv/src/lib.rs
=> aes-gcm-siv v0.1.0

aes-gcm-siv/Cargo.toml, aes-gcm/CHANGELOG.md, aes-gcm/Cargo.toml
=> aes-gcm v0.1.0

README.md, aes-siv/CHANGELOG.md, aes-siv/Cargo.toml
=> aes-siv v0.1.1

chacha20poly1305/CHANGELOG.md, chacha20poly1305/Cargo.toml
=> chacha20poly1305 v0.2.2

xsalsa20poly1305/CHANGELOG.md, xsalsa20poly1305/Cargo.toml
=> xsalsa20poly1305 v0.2.1

ring/CHANGELOG.md, ring/Cargo.toml
=> ring-aead v0.1.0

xsalsa20poly1305/CHANGELOG.md, xsalsa20poly1305/Cargo.toml, xsalsa20poly1305/src/lib.rs
- Upgrade `salsa20` crate to v0.4 ([#71])
[#71]: https://github.com/RustCrypto/AEADs/pull/71
=> xsalsa20poly1305 v0.3.1

aes-gcm-siv/src/ctr.rs, aes-gcm-siv/src/lib.rs
Makes `Ctr` a generic parameter which can be implemented for various different `BlockCipher::ParBlocks`.
=> aes-gcm-siv: support generic `Ctr` implementation

aes-gcm-siv/src/ctr.rs, aes-gcm-siv/src/lib.rs
Support for using AES-GCM-SIV with AES implementations which operate on one-block-at-a-time, which is useful for embedded contexts.
=> aes-gcm-siv: add CTR mode implementation for ParBlocks=U1

aes-gcm/src/ctr.rs, aes-gcm/src/lib.rs
Makes all bounds on `ParBlocks` generic, allowing them to operate over any number of parallel blocks.
=> aes-gcm: make `Ctr32` generic around `BlockCipher::ParBlocks`

chacha20poly1305/CHANGELOG.md, chacha20poly1305/Cargo.toml
- `chacha20` cargo feature; ; replace macros with generics ([#99])
[#99]: https://github.com/RustCrypto/AEADs/pull/99
=> chacha20poly1305 v0.4.0

Cargo.lock, chacha20poly1305/CHANGELOG.md, chacha20poly1305/Cargo.toml
- `Clone` impl on `ChaChaPoly1305` ([#103])
[#103]: https://github.com/RustCrypto/AEADs/pull/103
=> chacha20poly1305 v0.4.1

README.md
=> README.md: remove deps.rs image

.github/workflows/security-audit.yml
Wrong branch; formatting cleanups
=> .github: security audit fixups

.github/workflows/aes-gcm-siv.yml, .github/workflows/aes-gcm.yml, .github/workflows/aes-siv.yml, .github/workflows/chacha20poly1305.yml, .github/workflows/crypto_box.yml, .github/workflows/ring-aead.yml, .github/workflows/xsalsa20poly1305.yml, Cargo.lock
This matches the GitHub Actions config with the other RustCrypto repos
=> .github: use condensed configuration

Cargo.lock, Cargo.toml, crypto_box/Cargo.toml, crypto_box/src/lib.rs, crypto_box/tests/lib.rs, xsalsa20poly1305/Cargo.toml, xsalsa20poly1305/src/lib.rs, xsalsa20poly1305/tests/lib.rs
Upgrades to the `aead` v0.3.0-pre crate.
=> xsalsa20poly1305 + crypto_box: `aead` crate upgrade

aes-gcm-siv/README.md, aes-gcm/README.md, chacha20poly1305/README.md, crypto_box/README.md, ring-aead/README.md, xsalsa20poly1305/README.md
- Add "RustCrypto:" to all headlines
- Move crate badges to a separate line
=> README.md: formatting fixups

aes-gcm-siv/benches/aes-gcm-siv.rs, aes-gcm/benches/aes-gcm.rs, chacha20poly1305/benches/chacha20poly1305.rs
Building the benchmarks was broken. This fixes it.
=> Fix benchmarks

mgm/src/lib.rs
Noticed [here](https://github.com/RustCrypto/AEADs/pull/185#discussion_r467136115).
=> Fix MGM doc example

Cargo.lock, mgm/CHANGELOG.md, mgm/Cargo.toml, mgm/src/lib.rs
=> mgm: update block-cipher to v0.8

Cargo.lock, chacha20poly1305/CHANGELOG.md, chacha20poly1305/Cargo.toml
- Expand README.md ([#233])
[#233]: https://github.com/RustCrypto/AEADs/pull/233
=> chacha20poly1305 v0.7.1

Cargo.lock, chacha20poly1305/Cargo.toml
https://github.com/RustCrypto/stream-ciphers/pull/215
=> chacha20poly1305: update `xchacha` feature name

Cargo.lock, crypto_box/Cargo.toml, crypto_box/src/lib.rs, crypto_box/tests/lib.rs, xsalsa20poly1305/Cargo.toml
=> Bump `rand_core` crate dependency to v0.6

Cargo.lock, deoxys/CHANGELOG.md, deoxys/Cargo.toml
=> deoxys v0.0.1

Cargo.lock, ccm/CHANGELOG.md, ccm/Cargo.toml, ccm/src/lib.rs, ccm/src/traits.rs
=> ccm: expose NonceSize and TagSize traits

aes-gcm-siv/Cargo.toml, aes-gcm/Cargo.toml, aes-siv/Cargo.toml, deoxys/Cargo.toml, xsalsa20poly1305/Cargo.toml
Per https://github.com/RustCrypto/utils/issues/723#issuecomment-1068081155
=> Unpin `zeroize` version

aes-gcm/src/lib.rs, ccm/src/lib.rs, eax/src/lib.rs, eax/src/online.rs
This approach is a bit more readable and straightforward
=> Replace `Choice::unwrap_u8` calls with `Into`

xsalsa20poly1305/README.md
I copied the wording from [chacha20poly1305's README](https://github.com/RustCrypto/AEADs/tree/master/chacha20poly1305).
=> xsalsa20poly1305: Update note about audit

xsalsa20poly1305/README.md
Oops, I forgot to adjust the heading in #473 😄
=> xsalsa20poly1305: Fix README

aes-gcm/src/lib.rs
=> aes-gcm: improve doc example

aes-siv/src/siv.rs
Inspired by https://github.com/RustCrypto/AEADs/pull/506
=> aes-siv: minor code improvement

.github/workflows/workspace.yml
=> Disable codecov CI job

ascon-aead/Cargo.toml, ascon-aead/src/lib.rs
Add arrayvec, getrandom, rand_core and stream features.
=> ascon: align features with other AEAD crates

.github/workflows/eax.yml
to ensure that no error creep in by mistake
=> add a test run with --no-default-features to eax

.github/workflows/aes-gcm-siv.yml, .github/workflows/aes-siv.yml, .github/workflows/benches.yml, .github/workflows/ccm.yml, .github/workflows/chacha20poly1305.yml, .github/workflows/deoxys.yml, .github/workflows/eax.yml, .github/workflows/mgm.yml
Adds each of the workflow config files to their own `on`..`paths:` so changes to a workflow's configuration run the respective workflow.
=> CI: run workflows when their config files change

.github/workflows/aes-gcm-siv.yml, .github/workflows/aes-gcm.yml, .github/workflows/aes-siv.yml, .github/workflows/ascon-aead.yml, .github/workflows/ccm.yml, .github/workflows/deoxys.yml, .github/workflows/eax.yml, .github/workflows/mgm.yml, aes-gcm-siv/tests/aes128gcmsiv.rs, aes-gcm-siv/tests/aes256gcmsiv.rs, aes-gcm-siv/tests/ctr_wrap.rs, aes-gcm/src/lib.rs, aes-gcm/tests/aes128gcm.rs, aes-gcm/tests/aes256gcm.rs, aes-gcm/tests/other_ivlen.rs, aes-siv/tests/aead.rs, aes-siv/tests/siv.rs, ccm/tests/mod.rs, deoxys/tests/deoxys_i_128.rs, deoxys/tests/deoxys_i_256.rs, deoxys/tests/deoxys_ii_128.rs, deoxys/tests/deoxys_ii_256.rs, mgm/tests/bad_nonce.rs, mgm/tests/rfc9058.rs
Ensures all of the tests pass even when default features are disabled
=> CI: test all crates with `--no-default-features`

ocb3/src/lib.rs
Changes the bounds from using a sealed trait to the `IsLessOrEqual` operator, which both better reflects the constraints as well as makes it easier to eventually translate to const generics.
=> ocb3: use `IsLessOrEqual` for `NonceSize`/`TagSize`

ocb3/CHANGELOG.md, ocb3/Cargo.toml
=> ocb3 v0.1.0

chacha20poly1305/src/lib.rs, chacha20poly1305/tests/lib.rs
=> Update URL to match redirect in lib.rs

.github/workflows/aead-stream.yml, .github/workflows/aes-gcm-siv.yml, .github/workflows/aes-gcm.yml, .github/workflows/aes-siv.yml, .github/workflows/ascon-aead.yml, .github/workflows/ccm.yml, .github/workflows/chacha20poly1305.yml, .github/workflows/deoxys.yml, .github/workflows/eax.yml, .github/workflows/ocb3.yml, Cargo.lock, aead-stream/Cargo.toml, aes-gcm-siv/Cargo.toml, aes-gcm/Cargo.toml, aes-siv/Cargo.toml, ascon-aead/Cargo.toml, ccm/Cargo.toml, chacha20poly1305/Cargo.toml, deoxys/Cargo.toml, eax/Cargo.toml, ocb3/Cargo.toml
=> build(deps): bump hybrid-array from 0.2.0-rc.9 to 0.2.0-rc.10; bump MSRV to 1.81

chacha20poly1305/README.md
=> chacha20poly1305: fix security audit link

aes-gcm-siv/Cargo.toml, aes-gcm-siv/src/lib.rs, aes-siv/Cargo.toml, aes-siv/src/siv.rs, chacha20poly1305/Cargo.toml, chacha20poly1305/src/cipher.rs, chacha20poly1305/src/lib.rs, deoxys/Cargo.toml, deoxys/src/lib.rs
=> Make zeroize optional for all crates

ascon-aead/CHANGELOG.md, ascon-aead/src/asconcore.rs, ascon-aead/tests/kats_test.rs
=> ascon-aead: zeroize buffer during decryption on failed tag check

deoxys/src/modes.rs
This is split off from https://github.com/RustCrypto/AEADs/pull/666
=> deoxys: reorganize `authenticate_message`

belt-dwp/src/gf/utils.rs, belt-dwp/src/ghash.rs, belt-dwp/src/lib.rs
* Removed unused allow_unused
* Replaced xor_s -> update_padded
=> fix: cleanup belt-dwp

.github/workflows/aead-stream.yml, .github/workflows/aes-gcm-siv.yml, .github/workflows/aes-gcm.yml, .github/workflows/aes-siv.yml, .github/workflows/ascon-aead128.yml, .github/workflows/belt-dwp.yml, .github/workflows/benches.yml, .github/workflows/ccm.yml, .github/workflows/chacha20poly1305.yml, .github/workflows/deoxys.yml, .github/workflows/eax.yml, .github/workflows/mgm.yml, .github/workflows/ocb3.yml, .github/workflows/workspace.yml, .github/workflows/xaes-256-gcm.yml
Same as https://github.com/RustCrypto/traits/pull/1948.
=> Only run CI on latest commit of PR branches.
